/*
Copyright (C) April 2014 Mehboub Sophian

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Adresses generated by hbm2java
 */

public class Adresses implements java.io.Serializable {

	@Override
	public String toString() {
		return "Adresses [idAdresse=" + idAdresse + ", rue=" + rue + ", code="
				+ code + ", ville=" + ville + "]";
	}

	private Integer idAdresse;
	private String rue;
	private String code;
	private String ville;
	private Set userses = new HashSet(0);

	public Adresses() {
	}

	public Adresses(String rue, String code, String ville) {
		this.rue = rue;
		this.code = code;
		this.ville = ville;
	}

	public Adresses(String rue, String code, String ville, Set userses) {
		this.rue = rue;
		this.code = code;
		this.ville = ville;
		this.userses = userses;
	}

	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	public String getRue() {
		return this.rue;
	}

	public void setRue(String rue) {
		this.rue = rue;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
