/*
Copyright (C) April 2014 Mehboub Sophian

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Contacts generated by hbm2java
 */
public class Contacts implements java.io.Serializable {

	private Integer idContact;
	private String entreprise;
	private String contact;
	private String adresse;
	private String commune;
	private String email;
	private String tel;
	private Set rdvses = new HashSet(0);
	private Set annonceses = new HashSet(0);

	public Contacts() {
	}
	

	public Contacts(String entreprise, String contact,
			String adresse, String commune, String email, String tel,
			Set rdvses, Set annonceses) {
		super();
		this.idContact = idContact;
		this.entreprise = entreprise;
		this.contact = contact;
		this.adresse = adresse;
		this.commune = commune;
		this.email = email;
		this.tel = tel;
		this.rdvses = rdvses;
		this.annonceses = annonceses;
	}



	public Integer getIdContact() {
		return this.idContact;
	}

	public void setIdContact(Integer idContact) {
		this.idContact = idContact;
	}

	public String getEntreprise() {
		return this.entreprise;
	}

	public void setEntreprise(String entreprise) {
		this.entreprise = entreprise;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getCommune() {
		return this.commune;
	}

	public void setCommune(String commune) {
		this.commune = commune;
	}

	public Set getRdvses() {
		return this.rdvses;
	}

	public void setRdvses(Set rdvses) {
		this.rdvses = rdvses;
	}

	public Set getAnnonceses() {
		return this.annonceses;
	}

	public void setAnnonceses(Set annonceses) {
		this.annonceses = annonceses;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getTel() {
		return tel;
	}


	public void setTel(String tel) {
		this.tel = tel;
	}

}
