/*
Copyright (C) April 2014 Mehboub Sophian

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

/**
 * RdvsId generated by hbm2java
 */
public class RdvsId implements java.io.Serializable {

	private int idRdv;
	private int idUser;
	private int idContact;

	public RdvsId() {
	}

	public RdvsId(int idRdv, int idUser, int idContact) {
		this.idRdv = idRdv;
		this.idUser = idUser;
		this.idContact = idContact;
	}

	public int getIdRdv() {
		return this.idRdv;
	}

	public void setIdRdv(int idRdv) {
		this.idRdv = idRdv;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdContact() {
		return this.idContact;
	}

	public void setIdContact(int idContact) {
		this.idContact = idContact;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RdvsId))
			return false;
		RdvsId castOther = (RdvsId) other;

		return (this.getIdRdv() == castOther.getIdRdv())
				&& (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdContact() == castOther.getIdContact());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRdv();
		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdContact();
		return result;
	}

}
