/*
Copyright (C) April 2014 Mehboub Sophian

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang3.StringEscapeUtils;

/**
 * Metiers generated by hbm2java
 */
public class Metiers implements java.io.Serializable {

	private Integer idMetier;
	private String metier;
	private Set userACommeMetiers = new HashSet(0);
	private Set annonceses = new HashSet(0);

	public Metiers() {
	}

	@Override
	public String toString() {
		return StringEscapeUtils.unescapeHtml4(metier);
	}

	public Metiers(String metier) {
		this.metier = metier;
	}

	public Metiers(String metier, Set userACommeMetiers, Set annonceses) {
		this.metier = metier;
		this.userACommeMetiers = userACommeMetiers;
		this.annonceses = annonceses;
	}

	public Integer getIdMetier() {
		return this.idMetier;
	}

	public void setIdMetier(Integer idMetier) {
		this.idMetier = idMetier;
	}

	public String getMetier() {
		return StringEscapeUtils.unescapeHtml4(this.metier);
	}

	public void setMetier(String metier) {
		this.metier = metier;
	}

	public Set getUserACommeMetiers() {
		return this.userACommeMetiers;
	}

	public void setUserACommeMetiers(Set userACommeMetiers) {
		this.userACommeMetiers = userACommeMetiers;
	}

	public Set getAnnonceses() {
		return this.annonceses;
	}

	public void setAnnonceses(Set annonceses) {
		this.annonceses = annonceses;
	}

}
