/*
Copyright (C) April 2014 Mehboub Sophian

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

/**
 * UserACommeMetierId generated by hbm2java
 */
public class UserACommeMetierId implements java.io.Serializable {

	private int idUser;
	private int idMetier;

	public UserACommeMetierId() {
	}

	public UserACommeMetierId(int idUser, int idMetier) {
		this.idUser = idUser;
		this.idMetier = idMetier;
	}

	@Override
	public String toString() {
		return "UserACommeMetierId [idUser=" + idUser + ", idMetier="
				+ idMetier + "]";
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdMetier() {
		return this.idMetier;
	}

	public void setIdMetier(int idMetier) {
		this.idMetier = idMetier;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserACommeMetierId))
			return false;
		UserACommeMetierId castOther = (UserACommeMetierId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdMetier() == castOther.getIdMetier());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdMetier();
		return result;
	}

}
