/*
Copyright (C) April 2014 Mehboub Sophian

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

package com.interim.model;
// default package
// Generated 06-mai-2014 5:17:18 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	@Override
	public String toString() {
		return "Users [idUser=" + idUser + ", nom=" + nom
				+ ", prenom=" + prenom + ", tel=" + tel + ", adresses=" + adresses + ", logins=" + logins
				+ ", rdvses=" + rdvses
				+ ", userACommeMetiers=" + userACommeMetiers + "]";
	}

	private Integer idUser = null;
	private Logins logins = new Logins();
	private Adresses adresses = new Adresses();
	private String nom;
	private String prenom;
	private String email;
	private String role;
	private String tel;
	private Set rdvses = new HashSet(0);
	private Set userACommeMetiers = new HashSet(0);

	public Users() {
	}

	public Users(Logins logins, Adresses adresses, String nom, String prenom, String email, String role,
			String tel) {
		this.logins = logins;
		this.adresses = adresses;
		this.nom = nom;
		this.prenom = prenom;
		this.tel = tel;
	}

	public Users(Logins logins, Adresses adresses, String nom,
			String prenom, String email, String role, String tel, Set rdvses, Set userACommeMetiers) {
		this.logins = logins;
		this.adresses = adresses;
		this.nom = nom;
		this.prenom = prenom;
		this.tel = tel;
		this.rdvses = rdvses;
		this.userACommeMetiers = userACommeMetiers;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}


	public Logins getLogins() {
		return this.logins;
	}

	public void setLogins(Logins logins) {
		this.logins = logins;
	}

	public Adresses getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Adresses adresses) {
		this.adresses = adresses;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Set getRdvses() {
		return this.rdvses;
	}

	public void setRdvses(Set rdvses) {
		this.rdvses = rdvses;
	}

	public Set getUserACommeMetiers() {
		return this.userACommeMetiers;
	}

	public void setUserACommeMetiers(Set userACommeMetiers) {
		this.userACommeMetiers = userACommeMetiers;
	}


	public Boolean isLogin() {
		if(idUser!=0 && idUser!=null)
		return true;
		else return false;
		
	}
}
